version: 1.2
workflows:
   - subclass: WDL
     primaryDescriptorPath: /Dockstore.wdl
     testParameterFiles:
         - /Dockstore.json
     name: samtools-view
   - subclass: WDL
     primaryDescriptorPath: /Dockstore_bam2cram.wdl
     testParameterFiles:
         - /Dockstore.json
     name: samtools-bam2cram